when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: [ "*.ex", "*.eex", "*.exs", "mix.lock", ".woodpecker/**" ]

depends_on:
  - docker-develop

skip_clone: true

steps:
  docker-develop-combine:
    image: git.fluffytail.org/phnt/wpc-docker-tagger:latest
    settings:
      registry: "git.fluffytail.org"
      image: "pleroma-test/pleroma"
      architectures: [amd64, arm64]
      tags:
        - latest
        - develop
        - ${CI_COMMIT_SHA}
      username:
        from_secret: pleroma-ci-user
      password:
        from_secret: pleroma-ci-password
