when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: [ "*.ex", "*.eex", "*.exs", "mix.lock", ".woodpecker/**" ]

matrix:
  platform:
    - linux/amd64
    - linux/arm64

# This is needed for the when clauses below.
# When the platform clause is fixed, this might not be needed anymore
labels:
  platform: ${platform}

variables:
  docker_variables: &docker_variables
    repo: pleroma/pleroma
    registry: git.pleroma.social
    username:
      from_secret: pleroma-ci-user
    password:
      from_secret: pleroma-ci-password

steps:
  docker-develop-amd64:
    image: woodpeckerci/plugin-kaniko:2.3.1
    # when:
    #   - platform: linux/amd64
    # does not work even though it should according to docs
    # https://github.com/woodpecker-ci/woodpecker/discussions/5367#discussioncomment-13901342
    when:
      - evaluate: platform == "linux/amd64"
    settings:
      <<: *docker_variables
      tags:
        - latest-amd64
        - develop-amd64
        - ${CI_COMMIT_SHA}-amd64

  docker-develop-arm64:
    image: woodpeckerci/plugin-kaniko:2.3.1
    when:
      - evaluate: platform == "linux/arm64"
    settings:
      <<: *docker_variables
      tags:
        - latest-arm64
        - develop-arm64
        - ${CI_COMMIT_SHA}-arm64
