when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: [ "*.ex", "*.eex", "*.exs", "mix.lock", ".woodpecker/**" ]
  - event: push
    branch: stable
    path: [ "*.ex", "*.eex", "*.exs", "mix.lock", ".woodpecker/**" ]
  - event: tag
  - event: manual
    branch: stable

depends_on:
  - docker

skip_clone: true

steps:
  docker-develop-combine:
    image: git.fluffytail.org/phnt/wpc-docker-tagger:latest
    when:
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
    settings:
      registry: "git.pleroma.social"
      image: "pleroma/pleroma"
      architectures: [amd64, arm64]
      tags:
        - latest
        - develop
        - ${CI_COMMIT_SHA:0:8}
      username:
        from_secret: pleroma-ci-user
      password:
        from_secret: pleroma-ci-password

  docker-stable-combine:
    image: git.fluffytail.org/phnt/wpc-docker-tagger:latest
    when:
      - event: push
        branch: stable
      - evaluate: 'CI_PIPELINE_EVENT == "manual" && CI_COMMIT_BRANCH == "stable" && CI_COMMIT_TAG == ""'
    settings: &docker_settings
      registry: "git.pleroma.social"
      image: "pleroma/pleroma"
      architectures: [amd64, arm64]
      tags: &docker_tags
        - latest
        - stable
        - ${CI_COMMIT_SHA:0:8}
      username:
        from_secret: pleroma-ci-user
      password:
        from_secret: pleroma-ci-password

  docker-stable-tag-combine:
    image: git.fluffytail.org/phnt/wpc-docker-tagger:latest
    when:
      - event: tag
      - evaluate: 'CI_PIPELINE_EVENT == "manual" && CI_COMMIT_BRANCH == "stable" && CI_COMMIT_TAG != ""'
    settings:
      <<: *docker_settings
      tags:
        - <<: *docker_tags
        - ${CI_COMMIT_TAG}
