when:
  - event: pull_request

depends_on:
  - changelog

steps:
  mix-format:
    image: &elixir-image
      docker.io/elixir:1.15-alpine
    failure: ignore
    commands:
      - |
        if ! mix format --check-formatted; then
          touch fail.stamp
        fi

  credo:
    image: *elixir-image
    failure: ignore
    environment:
      MIX_ENV: test
    commands:
      - apk add --no-cache build-base cmake exiftool ffmpeg file-dev git openssl
      - adduser -D -h /home/testuser testuser
      - mkdir -p /home/testuser/.mix /home/testuser/.hex
      - chown -R testuser:testuser . /home/testuser
      - su testuser -c "HOME=/home/testuser mix local.hex --force"
      - su testuser -c "HOME=/home/testuser mix local.rebar --force"
      - su testuser -c "HOME=/home/testuser mix deps.get"
      - |
        if ! su testuser -c "HOME=/home/testuser mix analyze" && ! test -f fail.stamp; then
          touch fail.stamp
        fi

  cycles:
    image: *elixir-image
    failure: ignore
    commands:
      - |
        if ! mix xref graph --format cycles --label compile | awk '{print $0} END{exit ($0 != "No cycles found")}' && test -f fail.stamp; then
        touch fail.stamp
        fi

  ensure-status:
    image: *elixir-image
    commands: |
      if test -f fail.stamp; then
        echo "One or more previous steps fails. Failing workflow..."
        exit 1
      else
        echo "All steps passed"
        exit 0
      fi
