when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: [ "*.ex", "*.eex", "*.exs", "mix.lock", ".woodpecker/**" ]
  - event: tag
  - event: manual
    branch: stable

matrix:
  platform:
    - linux/amd64
    - linux/arm64

# This is needed for the when clauses below.
# When the platform clause is fixed, this might not be needed anymore
labels:
  platform: ${platform}

variables:
  build_cmds: &build_cmds
    - apk add git build-base cmake file-dev openssl vips-dev zip
    - echo "import Config" > config/prod.secret.exs
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only prod
    - mkdir release
    - export PLEROMA_BUILD_BRANCH=${CI_COMMIT_BRANCH}
    - mix release --path release
  build_image_amd64: &build_image_amd64 docker.io/hexpm/elixir-amd64:1.17.3-erlang-27.3.4.2-alpine-3.22.1
  build_image_arm64: &build_image_arm64 docker.io/hexpm/elixir-arm64:1.17.3-erlang-27.3.4.2-alpine-3.22.1
  artifacts_uploader_image: &artifacts_uploader_image docker.io/woodpeckercommunity/plugin-gitea-package:0.5.0
  artifacts_uploader_settings: &artifacts_uploader_settings
    user:
      from_secret: pleroma-ci-user
    password:
      from_secret: pleroma-ci-password
    owner: 'pleroma'
  env: &env
    MIX_ENV: prod
    VIX_COMPILATION_MODE: PLATFORM_PROVIDED_LIBVIPS

steps:
  otp-develop-amd64-musl:
    image: *build_image_amd64
    when:
      - evaluate: 'platform == "linux/amd64" && CI_COMMIT_BRANCH == "${CI_REPO_DEFAULT_BRANCH}"'
    environment: *env
    commands: &amd64_build
      - <<: *build_cmds
      - zip -9rq ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-amd64-musl.zip release

  otp-stable-amd64-musl:
    image: *build_image_amd64
    when:
      - evaluate: 'platform == "linux/amd64" && CI_PIPELINE_EVENT == "manual" && CI_COMMIT_BRANCH == "stable"'
    environment: *env
    commands: *amd64_build

  # Tag events don't have CI_COMMIT_BRANCH set, hardcode stable
  otp-stable-tag-amd64-musl:
    image: *build_image_amd64
    when:
      - evaluate: 'platform == "linux/amd64" && CI_PIPELINE_EVENT == "tag"'
    environment: *env
    commands:
      - <<: *build_cmds
      - zip -9rq stable-${CI_COMMIT_SHA:0:8}-amd64-musl.zip release

  otp-develop-arm64-musl:
    image: *build_image_arm64
    when:
      - evaluate: 'platform == "linux/arm64" && CI_COMMIT_BRANCH == "${CI_REPO_DEFAULT_BRANCH}"'
    environment: *env
    commands: &arm64_build
      - <<: *build_cmds
      - zip -9rq ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-arm64-musl.zip release

  otp-stable-arm64-musl:
    image: *build_image_arm64
    when:
      - evaluate: 'platform == "linux/arm64" && CI_PIPELINE_EVENT == "manual" && CI_COMMIT_BRANCH == "stable"'
    environment: *env
    commands: *arm64_build

  # Tag events don't have CI_COMMIT_BRANCH set, hardcode stable
  otp-stable-tag-arm64-musl:
    image: *build_image_arm64
    when:
      - evaluate: 'platform == "linux/arm64" && CI_PIPELINE_EVENT == "tag"'
    environment: *env
    commands:
      - <<: *build_cmds
      - zip -9rq stable-${CI_COMMIT_SHA:0:8}-arm64-musl.zip release

  upload-artifacts-amd64-musl:
    image: *artifacts_uploader_image
    when:
      - evaluate: 'platform == "linux/amd64" && CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "${CI_REPO_DEFAULT_BRANCH}"'
      - evaluate: 'platform == "linux/amd64" && CI_PIPELINE_EVENT == "manual"'
    settings:
      <<: *artifacts_uploader_settings
      package_name: pleroma-otp-${CI_COMMIT_BRANCH}-amd64-musl
      package_version: ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-amd64-musl
      file_source: ./${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-amd64-musl.zip
      file_name: ./pleroma-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-amd64-musl.zip

  # Tag events don't have CI_COMMIT_BRANCH set, hardcode stable
  upload-artifacts-tag-amd64-musl:
    image: *artifacts_uploader_image
    when:
      - evaluate: 'platform == "linux/amd64" && CI_PIPELINE_EVENT == "tag"'
    settings:
      <<: *artifacts_uploader_settings
      package_name: pleroma-otp-stable-amd64-musl
      package_version: stable-${CI_COMMIT_SHA:0:8}-amd64-musl
      file_source: ./stable-${CI_COMMIT_SHA:0:8}-amd64-musl.zip
      file_name: ./pleroma-stable-${CI_COMMIT_SHA:0:8}-amd64-musl.zip

  upload-artifacts-arm64-musl:
    image: *artifacts_uploader_image
    when:
      - evaluate: 'platform == "linux/arm64" && CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "${CI_REPO_DEFAULT_BRANCH}"'
      - evaluate: 'platform == "linux/arm64" && CI_PIPELINE_EVENT == "manual"'
    settings:
      <<: *artifacts_uploader_settings
      package_name: pleroma-otp-${CI_COMMIT_BRANCH}-arm64-musl
      package_version: ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-arm64-musl
      file_source: ./${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-arm64-musl.zip
      file_name: ./pleroma-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHA:0:8}-arm64-musl.zip

  # Tag events don't have CI_COMMIT_BRANCH set, hardcode stable
  upload-artifacts-tag-arm64-musl:
    image: *artifacts_uploader_image
    when:
      - evaluate: 'platform == "linux/arm64" && CI_PIPELINE_EVENT == "tag"'
    settings:
      <<: *artifacts_uploader_settings
      package_name: pleroma-otp-stable-arm64-musl
      package_version: stable-${CI_COMMIT_SHA:0:8}-arm64-musl
      file_source: ./stable-${CI_COMMIT_SHA:0:8}-arm64-musl.zip
      file_name: ./pleroma-stable-${CI_COMMIT_SHA:0:8}-arm64-musl.zip
