name: docker

on:
  push:
    branches:
      - 'pl.kpherox.dev'
  pull_request:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  ELIXIR_VER: '1.17.3'
  ERLANG_VER: '27.1.2'
  ALPINE_VER: '3.20.3'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Platform metadata
        id: platform
        run: |
          case "${{ runner.arch }}" in
            "X64")
              echo "docker=linux/amd64" >> "$GITHUB_OUTPUT"
              echo "digest-name=digest-amd64" >> "$GITHUB_OUTPUT"
              echo "digest-file=digest-amd64.txt" >> "$GITHUB_OUTPUT"
            ;;
            "ARM64")
              echo "docker=linux/arm64" >> "$GITHUB_OUTPUT"
              echo "digest-name=digest-arm64" >> "$GITHUB_OUTPUT"
              echo "digest-file=digest-arm64.txt" >> "$GITHUB_OUTPUT"
            ;;
          esac

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          annotations: "org.opencontainers.image.licenses=AGPL-3.0-only"
          labels: "org.opencontainers.image.licenses=AGPL-3.0-only"

      - run: rm -rf package.json package-lock.json node_modules

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ step.platform.outputs.docker }}
          build-args: |
            ERL_FLAGS=${{ env.ERL_FLAGS }}
            ELIXIR_VER=${{ env.ELIXIR_VER }}
            ERLANG_VER=${{ env.ERLANG_VER }}
            ALPINE_VER=${{ env.ALPINE_VER }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          labels: ${{ steps.metadata.outputs.labels }}
          provenance: false
          outputs: type=image,oci-mediatypes=true,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

      - run: echo "${{ steps.build.outputs.digest }}" > ${{ step.platform.outputs.digest-file }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ step.platform.outputs.digest-name }}
          path: ${{ step.platform.outputs.digest-file }}

  merge:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
    needs:
      - build

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: digests
          pattern: digest-*
          merge-multiple: true

      - name: Get digests
        id: digests
        run: |
          {
            echo 'result<<EOF'
            find digests -name 'digest-*.txt' -exec cat {} \;
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          annotations: "org.opencontainers.image.licenses=AGPL-3.0-only"
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        uses: kphrx/docker-buildx-imagetools-action@v0.1.2
        with:
          annotations: ${{ steps.metadata.outputs.annotations }}
          sources: ${{ steps.digests.outputs.result }}
          tags: ${{ steps.metadata.outputs.tags }}
