name: docker

on:
  push:
    branches:
      - 'pl.kpherox.dev'
  pull_request:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  ELIXIR_VER: '1.14.5'
  ERLANG_VER: '26.0.2'
  ALPINE_VER: '3.18.2'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          labels: |
            org.opencontainers.image.licenses=AGPL-3.0-only

      - run: rm -rf package.json package-lock.json node_modules

      - name: Set up QEMU
        if: matrix.platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v3

      - name: Setup erl flags for QEMU
        if: matrix.platform == 'linux/arm64'
        run: |
          echo "ERL_FLAGS=+JPperf true" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          build-args: |
            ERL_FLAGS=${{ env.ERL_FLAGS }}
            ELIXIR_VER=${{ env.ELIXIR_VER }}
            ERLANG_VER=${{ env.ERLANG_VER }}
            ALPINE_VER=${{ env.ALPINE_VER }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          labels: ${{ steps.metadata.outputs.labels }}
          provenance: false
          outputs: type=image,oci-mediatypes=true,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

      - uses: cloudposse/github-action-matrix-outputs-write@0.4.2
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.platform }}
          outputs: |-
            digest: ${{ steps.build.outputs.digest }}

  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      - build

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@0.1.1
        id: read
        with:
          matrix-step-name: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          labels: |
            org.opencontainers.image.licenses=AGPL-3.0-only
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        uses: kphrx/docker-buildx-imagetools-action@v0.1.0
        with:
          annotations: ${{ steps.metadata.outputs.annotations }}
          sources: ${{ join(fromJson(steps.read.outputs.result).digest.*, ',') }}
          tags: ${{ steps.metadata.outputs.tags }}
