name: docker

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=latest
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION,,}"
          if [[ $GITHUB_REF = refs/tags/* ]] && [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:stable-latest"
          fi
          SHORT_SHA=$(git rev-parse --short HEAD)
          if [[ $GITHUB_REF != refs/tags/* ]] && [[ "${{ github.event_name }}" = "push" ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:${SHORT_SHA}"
          fi
          BUILD_ARGS="VCS_REF=${SHORT_SHA},BUILD_DATE=$(date --utc -Iseconds)"
          echo ::set-output name=build-args::${BUILD_ARGS}
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          load: false
          target: build
          cache-from: type=gha,scope=build
          cache-to: type=gha,scope=build,mode=max

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=gha,scope=prod
            type=gha,scope=build
          cache-to: type=gha,scope=prod,mode=max
          build-args: ${{ steps.prepare.outputs.build-args }}
          tags: ${{ steps.prepare.outputs.tags }}

  deployment:
    needs: docker
    runs-on: ubuntu-latest
    environment: 
      name: pl.kpherox.dev
      url: https://pl.kpherox.dev
    steps:
      - name: setup
        env:
          DOCKER_HOST: ssh://deploy_server
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          COMPOSE_YML: ${{ secrets.COMPOSE_YML }}
        run: |
          ssh-keyscan ${DEPLOY_SERVER} >> ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" >> ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "Host deploy_server
            HostName ${DEPLOY_SERVER}
            User ${DEPLOY_USER}
            IdentityFile ~/.ssh/deploy_key
          " >> ~/.ssh/config
          echo "${COMPOSE_YML}" >> ./compose.yml
          docker context ls
      - name: deploy
        run: |
          docker compose -p pleroma pull
          docker compose -p pleroma up -d
        
